### ISSUE TITLE
Up/Down key selection and mouse hover can end up with two highlights

### ISSUE THREAD

**Issue by darrenshrwd** [hakib/MassAutocomplete#18]
If you press down arrow it highlights first row, if you now hover the mouse it highlights the different row, but it leaves the highlight on the row highlighted by the up/down arrow keys.

There should only be one highlighted row when you hover it should replace the previously highlighted row.

(if you press an up or down arrow this should start from currently highlighted row even if that was highlighted by mouse)

**Comment by hakib** [comment]
Hey @darrenshrwd , You are right. This is intensional. 
Some of the other implementations are very expensive (digest wise) is that they use a hover event instead of a css hover to highlight the selected rows.

I usually work with the 80/20 rule for things like that. I think that most users would either use the keyboard or the mouse. As long as the user usses only one of them there is no problem. So, if I have to weigh what is more important - Performance or the 20% of (most probably developers during testing) using both keyboard and mouse i would go with performance. 

I'm open for other thought on that matter.

Haki.
