### ISSUE TITLE
Showing Message when There's not a result

### ISSUE THREAD

**Issue by mamos98** [hakib/MassAutocomplete#53]
How it is possible to show a message inside the results div when there's no result available? @hakib 
Thanks for your Great works on this library BTW.

**Comment by hakib** [comment]
Hey @mamos98, thanks.

There is not build in way of doing it. I never though of such a use case because i always treated the suggestion box as something you use while you type.

I think you can play around with the classes on the ac-container (when it's hidden for example) and add a pseudo element using CSS with the text you want.
