### ISSUE TITLE
Suggest not triggered after SPACE

### ISSUE THREAD

**Issue by guillaumegarcia13** [hakib/MassAutocomplete#63]
Hi,

The suggest function is not triggered when the user hit **space**.

In my app, I would like to implement a feature where I can look up the document I parsed for list of words so that: "development" and "development " give different suggestions.
Is this possible to trigger a new suggestion with ending space?

Thanks.

**Comment by hakib** [comment]
Hey @guillaumegarcia13 , 
You have total control over the suggest function.

In the examples in the site I trimmed `term` in my implementation of `suggest` because it made sense for me.  You don't have to do that in your implementation - you can produce different suggestions if there is a trailing white space.
